### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by 0zguner** [viatsko/lyn#8]
Does it support multi language systems like domain.com/en/ or domain.com/de/ for translated contents ?

**Comment by viatsko** [comment]
Not ready yet, but in the backlog.

I'm going to work on this part after introducing React + Redux stack completely for frontend, server-render for React is already there.

**Comment by 0zguner** [comment]
Wait what ? Does it render reactjs ?

**Comment by viatsko** [comment]
That's mentioned in README.md.

It's rendering reactjs using heavily updated reaxt for elixir inside.

**Comment by viatsko** [comment]
Ah, sorry, that's not explicit ¯_(ツ)_/¯.

Yeah, it's rendering react on server and supports hot-reloading for both using reaxt.
Designers love react, we love react, so yeah ¯_(ツ)_/¯

**Comment by 0zguner** [comment]
Does it only includes admin panel ?

**Comment by viatsko** [comment]
Only front-end. Admin panel is eex templates atm + REST-api

**Comment by viatsko** [comment]
imagine site has urls /, /news, /events, idea in the CMS (not implemented yet) is to provide you ability to build state-blocks for each url, for example / will be getting state.mainMenu, state.lastNews, /news will be getting state.mainMenu, state.newsList for example, kinda fluxish :)

**Comment by viatsko** [comment]
I'd recommend you to revisit this CMS after the weekend. I'll put a lot of effort to make all the planned things working. :ship:

**Comment by 0zguner** [comment]
I got the idea from the docs. I'm not sure if i would be happy with that kind of structure for my projects but hey, it sounds really cool. :)

**Comment by viatsko** [comment]
Still I'd strongly recommend you to revisit this thing after the weekend. :+1: 

I'm an UI/UX Developer with a strong Back-end past experience and I am able to tell why things are done in that or that way :P
